import {NextResponse} from 'next/server';
import {env} from 'cloudflare:workers';
import {requireMember} from '@/lib/server-auth';
const subjects=[
 {subject:'Matematik',solved:72,correct:53,wrong:15,blank:4,topics:['Doğrusal Denklemler','Eşitsizlikler']},
 {subject:'Türkçe',solved:84,correct:71,wrong:10,blank:3,topics:['Paragrafta Ana Düşünce','Fiilimsiler']},
 {subject:'Fen Bilimleri',solved:58,correct:44,wrong:11,blank:3,topics:['DNA ve Genetik Kod','Basınç']},
 {subject:'T.C. İnkılap Tarihi ve Atatürkçülük',solved:42,correct:33,wrong:7,blank:2,topics:['Millî Uyanış']},
 {subject:'Din Kültürü ve Ahlak Bilgisi',solved:35,correct:29,wrong:5,blank:1,topics:['Kader İnancı']},
 {subject:'İngilizce',solved:35,correct:24,wrong:8,blank:3,topics:['Friendship','Teen Life']},
];
async function askGemini(apiKey:string,model:string,prompt:string){const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.25,maxOutputTokens:280}})});if(!response.ok)throw new Error(`Gemini ${response.status}`);const data=await response.json();return data.candidates?.[0]?.content?.parts?.map((part:{text?:string})=>part.text??'').join('').trim()||''}
export async function POST(request:Request){try{await requireMember(request,env.DB,['guardian','coach'])}catch(error){if(error instanceof Response)return error;return NextResponse.json({error:'Yetkilendirme kontrolü başarısız.'},{status:500})}const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)return NextResponse.json({error:'Gemini anahtarı bulunamadı.'},{status:503});const {weekStart,weekEnd}=await request.json();if(!weekStart||!weekEnd)return NextResponse.json({error:'Hafta tarihleri eksik.'},{status:400});try{const branchReports=[];for(const item of subjects){const report=await askGemini(apiKey,'gemini-3.1-flash-lite',`Kimlik bilgisi kullanmadan bir LGS ${item.subject} branş koçu gibi değerlendir. Toplam ${item.solved}, doğru ${item.correct}, yanlış ${item.wrong}, boş ${item.blank}. Çalışılan konular: ${item.topics.join(', ')}. En fazla 80 kelimeyle güçlü yön, hata eğilimi, risk ve gelecek hafta için ölçülebilir öneri yaz. Veri dışı çıkarım yapma.`);branchReports.push({subject:item.subject,report})}const generalSummary=await askGemini(apiKey,'gemini-3.7-flash',`Aşağıdaki altı anonim branş raporunu veli ve gerçek eğitim koçu için birleştir. En fazla 170 kelime kullan. Genel ilerleme, en önemli iki öncelik, gelecek hafta çalışma dengesi ve koçun izlemesi gereken noktayı yaz. Tanı veya başarı garantisi verme.\n${branchReports.map(x=>`${x.subject}: ${x.report}`).join('\n')}`);return NextResponse.json({weekStart,weekEnd,branchReports,generalSummary,status:'draft'})}catch{return NextResponse.json({error:'Haftalık rapor hazırlanamadı. Ücretsiz kota veya model erişimini kontrol edin.'},{status:502})}}
