import {NextResponse} from 'next/server';
import {env} from 'cloudflare:workers';
import {requireMember} from '@/lib/server-auth';
type WeeklySubject={subject:string;solved:number;correct:number;wrong:number;blank:number;topics:string[]};
async function loadSubjects(weekStart:string,weekEnd:string):Promise<WeeklySubject[]>{
 const result=await env.DB.prepare('SELECT subject_id as subject, SUM(total) as solved, SUM(correct) as correct, SUM(wrong) as wrong, SUM(blank) as blank, GROUP_CONCAT(DISTINCT topic) as topics FROM study_results WHERE study_date BETWEEN ? AND ? GROUP BY subject_id').bind(weekStart,weekEnd).all<{subject:string;solved:number;correct:number;wrong:number;blank:number;topics:string|null}>();
 return result.results.map(item=>({...item,topics:item.topics?.split(',').filter(Boolean)??[]}));
}
async function askGemini(apiKey:string,model:string,prompt:string){const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.25,maxOutputTokens:280}})});if(!response.ok)throw new Error(`Gemini ${response.status}`);const data=await response.json();return data.candidates?.[0]?.content?.parts?.map((part:{text?:string})=>part.text??'').join('').trim()||''}
export async function POST(request:Request){try{await requireMember(request,env.DB,['guardian','coach'])}catch(error){if(error instanceof Response)return error;return NextResponse.json({error:'Yetkilendirme kontrolü başarısız.'},{status:500})}const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)return NextResponse.json({error:'Gemini anahtarı bulunamadı.'},{status:503});const {weekStart,weekEnd}=await request.json();if(!weekStart||!weekEnd)return NextResponse.json({error:'Hafta tarihleri eksik.'},{status:400});try{const subjects=await loadSubjects(weekStart,weekEnd);if(subjects.length===0)return NextResponse.json({error:'Bu hafta için henüz çalışma verisi bulunmuyor.'},{status:409});const branchReports=[];for(const item of subjects){const report=await askGemini(apiKey,'gemini-3.1-flash-lite',`Kimlik bilgisi kullanmadan bir LGS ${item.subject} branş koçu gibi değerlendir. Toplam ${item.solved}, doğru ${item.correct}, yanlış ${item.wrong}, boş ${item.blank}. Çalışılan konular: ${item.topics.join(', ')}. En fazla 80 kelimeyle güçlü yön, hata eğilimi, risk ve gelecek hafta için ölçülebilir öneri yaz. Veri dışı çıkarım yapma.`);branchReports.push({subject:item.subject,report})}const generalSummary=await askGemini(apiKey,'gemini-3.7-flash',`Aşağıdaki altı anonim branş raporunu veli ve gerçek eğitim koçu için birleştir. En fazla 170 kelime kullan. Genel ilerleme, en önemli iki öncelik, gelecek hafta çalışma dengesi ve koçun izlemesi gereken noktayı yaz. Tanı veya başarı garantisi verme.\n${branchReports.map(x=>`${x.subject}: ${x.report}`).join('\n')}`);return NextResponse.json({weekStart,weekEnd,branchReports,generalSummary,status:'draft'})}catch{return NextResponse.json({error:'Haftalık rapor hazırlanamadı. Ücretsiz kota veya model erişimini kontrol edin.'},{status:502})}}
