'use client';
import {useState} from 'react';
import {ArrowRight,BarChart3,BookOpen,Camera,Check,ChevronRight,Clock3,Flame,GraduationCap,House,ImagePlus,Lightbulb,Menu,MessageCircleMore,Play,Plus,Sparkles,Star,Target,TrendingUp,UsersRound,X} from 'lucide-react';
import {TopicsWorkspace} from '@/components/topics-workspace';
import {CoachWorkspace,type Assignment} from '@/components/coach-workspace';
import {WrongQuestionModal} from '@/components/wrong-question-modal';
import {ProgressDashboard} from '@/components/progress-dashboard';
import {currentWeekAssignments} from '@/lib/current-week-plan';

const subjects=[['Matematik','π','#7357c7','#eee9fb',0],['Türkçe','Aa','#ef725f','#ffebe6',0],['Fen','⚗','#238e89','#dff4ef',0],['İnkılap','✦','#d59a22','#fff2cf',0]] as const;
const coaches=[['MT','Matematik','Merve T.','Yeni değerlendirme','#7357c7'],['TÖ','Türkçe','Tolga Ö.','Rapor hazır','#ef725f'],['SA','Fen Bilimleri','Selin A.','İnceliyor','#238e89'],['EK','İnkılap Tarihi','Eren K.','Rapor hazır','#d59a22'],['DY','Din Kültürü','Derya Y.','Rapor hazır','#5377c6'],['CE','İngilizce','Cansu E.','Yeni değerlendirme','#a2589e']] as const;
function Ring({value}:{value:number}){return <div className="ring" style={{'--value':`${value*3.6}deg`} as React.CSSProperties}><div><strong>{value}</strong><span>%</span></div></div>}

export default function Home(){
 const [wrongOpen,setWrongOpen]=useState(false); const [view,setView]=useState<'student'|'adult'>('student'); const [section,setSection]=useState<'today'|'topics'|'assignments'|'progress'>('today'); const [open,setOpen]=useState(false); const [saved,setSaved]=useState(false); const [count,setCount]=useState(0); const [wrong,setWrong]=useState(0);
 const [assignments,setAssignments]=useState<Assignment[]>(currentWeekAssignments);
 const todayKey=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const todayAssignments=assignments.filter(item=>item.dueDate===todayKey);
 const todayTarget=todayAssignments.reduce((sum,item)=>sum+item.questionCount,0);
 const save=()=>{setSaved(true);setTimeout(()=>{setSaved(false);setOpen(false)},900)};
 return <main className="shell">
  <aside className="side"><a className="brand" href="#"><span>R</span></a><nav><button className={section==='today'?'active':''} onClick={()=>setSection('today')}><House/><i>Bugün</i></button><button className={(view==='student'?section==='topics':section==='assignments')?'active':''} onClick={()=>setSection(view==='student'?'topics':'assignments')}><Target/><i>{view==='student'?'Konularım':'Ödev Ver'}</i></button><button className={section==='progress'?'active':''} onClick={()=>setSection('progress')}><BarChart3/><i>Gelişim</i></button><button><UsersRound/><i>Koçlarım</i></button></nav><button className="mini">D</button></aside>
  <section className="workspace"><header className="top"><button className="hamb"><Menu/></button><div className="switch"><button className={view==='student'?'on':''} onClick={()=>{setView('student');setSection('today')}}>Deniz</button><button className={view==='adult'?'on':''} onClick={()=>{setView('adult');setSection('today')}}>Yetişkin & Koç</button></div><div className="topright"><span><Flame/> 0 günlük seri</span><b>S</b></div></header>
  {section==='progress'?<ProgressDashboard/>:view==='student'?(section==='topics'?<TopicsWorkspace/>:<div className="page">
   <div className="welcome"><div><p className="eyebrow">4–10 EYLÜL HAFTASI</p><h1>Selam Deniz! <span>Bugünkü çalışma rotan hazır.</span></h1></div></div>
   <section className="hero"><article className="daily"><div className="dailycopy"><span className="pill"><Sparkles/> BUGÜNÜN HEDEFİ</span><h2>{todayAssignments.length>0?<>Bugün {todayAssignments.length} görevde<br/>{todayTarget} soru seni bekliyor.</>:<>Bugün için atanmış<br/>bir çalışma bulunmuyor.</>}</h2><p>{todayAssignments.length>0?'Görevlerini tamamladıkça ilerlemen burada görünecek.':'Haftalık plandaki diğer günleri yetişkin ve koç alanından görebilirsin.'}</p></div><div className="dailyprogress"><Ring value={0}/><b>0 / {todayTarget} soru</b><small>{todayAssignments.length>0?`${todayTarget} soru kaldı`:'Bugün dinlenme günü'}</small></div></article>
   <article className="note"><div className="notehead"><span className="coachavatar">—</span><div><small>Koç değerlendirmesi</small><b>Henüz değerlendirme yok</b></div><MessageCircleMore/></div><blockquote>İlk çalışma verileri girildiğinde koç değerlendirmeleri burada görünecek.</blockquote></article></section>
   <section className="route"><Heading kicker="BUGÜNKÜ ROTA" title="Koçunun verdiği görevler" color="coral" extra={<span className="done">Salt okunur</span>}/><div className="tasks">{todayAssignments.length===0?<p>Bugün için ödev bulunmuyor.</p>:todayAssignments.map(item=><Task key={item.id} icon={item.subjectId==='matematik'?'π':'•'} color={item.subjectId==='matematik'?'purple':'teal'} top={item.subject.toUpperCase()+" · "+item.questionCount+" SORU"} title={item.topic} meta={[item.book,item.note].filter(Boolean).join(' · ')}/>)}</div></section>
   <section className="lower"><article className="weak"><Heading kicker="GÜÇLENDİRME ZAMANI" title="Birlikte toparlayalım" color="violet" extra={<Lightbulb/>}/><div className="weaktopic"><span>0<small>/100</small></span><div><small>VERİ BEKLENİYOR</small><b>Henüz güçlendirme konusu yok</b><p>Geçmiş çalışmalar girildiğinde öncelikli konular burada belirlenecek.</p></div></div></article>
   <article className="wrong"><span className="camera"><Camera/></span><div><p className="eyebrow tealtext">YANLIŞ DEFTERİM</p><h2>Takıldığın soruyu sakla</h2><p>Fotoğrafını çek, konusunu seç. Koçun görsün; zamanı gelince tekrar karşına çıksın.</p><button onClick={()=>setWrongOpen(true)}><ImagePlus/> Fotoğrafla soru ekle</button></div></article></section>
  </div>):section==='assignments'?<CoachWorkspace assignments={assignments} onAdd={item=>setAssignments(current=>[item,...current])}/>:<div className="page">
   <div className="welcome"><div><p className="eyebrow">HAFTALIK DEĞERLENDİRME · VERİ BEKLENİYOR</p><h1>Deniz’in haftası <span>bir bakışta.</span></h1></div><button className="outline" onClick={()=>setSection('assignments')}>Ödev ver <ArrowRight/></button></div>
   <section className="summaries"><Summary icon={<BookOpen/>} cls="violetbg" label="ÇÖZÜLEN SORU" value="0" detail="Veri yok"/><Summary icon={<Target/>} cls="coralbg" label="HAFTALIK DOĞRULUK" value="%0" detail="Veri yok"/><Summary icon={<GraduationCap/>} cls="tealbg" label="HAZIR KONULAR" value="0 / 0" detail="Veri yok"/></section>
   <section className="adultgrid"><article className="coachpanel"><Heading kicker="BRANŞ KOÇLARI" title="Uzman değerlendirmeleri" color="violet" extra={<span className="done">6 branş</span>}/><div className="coachtabs">{coaches.map((c,i)=><button key={c[1]} className={i===0?'selected':''} style={{'--coach':c[4]} as React.CSSProperties}><span>{c[0]}</span><div><b>{c[1]}</b><small>Veri bekleniyor</small></div></button>)}</div><div className="evaluation"><div className="evalhead"><span className="coachavatar large">—</span><div><small>HAFTALIK RAPOR</small><h3>Henüz değerlendirme oluşturulmadı</h3></div></div><p>Gerçek çalışma verileri girilip hafta kapatıldığında branş raporları burada görünecek.</p></div></article>
   <aside className="readiness"><Heading kicker="KONU HARİTASI" title="Hazır oluş" color="coral"/>{subjects.map(s=><div className="subject" key={s[0]}><span style={{background:s[3],color:s[2]}}>{s[1]}</span><div><b>{s[0]}</b><i><u style={{width:`${s[4]}%`,background:s[2]}}/></i></div><strong>{s[4]}</strong></div>)}<button className="link">Tüm konu haritası <ArrowRight/></button></aside></section>
  </div>}</section>
  {open&&<div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="modal" role="dialog" aria-modal="true"><button className="close" onClick={()=>setOpen(false)}><X/></button><span className="modalicon">π</span><p className="eyebrow">HIZLI KAYIT</p><h2>Ne çalıştın?</h2><label>Ders ve konu</label><button className="select"><span><b>Matematik</b><small>Doğrusal Denklemler</small></span><ChevronRight/></button><div className="numbers"><Counter label="Toplam soru" value={count} minus={()=>setCount(Math.max(0,count-5))} plus={()=>setCount(count+5)}/><Counter label="Yanlış" value={wrong} minus={()=>setWrong(Math.max(0,wrong-1))} plus={()=>setWrong(Math.min(count,wrong+1))}/></div><div className="result"><span><Check/> Doğru</span><b>{Math.max(0,count-wrong)}</b><span>Net</span><b>{(Math.max(0,count-wrong)-wrong/3).toFixed(2)}</b></div><button className={`save ${saved?'saved':''}`} onClick={save}>{saved?<><Check/> Kaydedildi!</>:<>Çalışmayı kaydet <ArrowRight/></>}</button></section></div>}
  <WrongQuestionModal open={wrongOpen} onClose={()=>setWrongOpen(false)}/>
 </main>
}
function Heading({kicker,title,color,extra}:{kicker:string,title:string,color:string,extra?:React.ReactNode}){return <div className="heading"><div><p className={`eyebrow ${color}`}>{kicker}</p><h2>{title}</h2></div>{extra}</div>}
function Task({done,icon,color,top,title,meta}:{done?:boolean,icon:string,color:string,top:string,title:string,meta:string}){return <article className={`task ${done?'complete':''}`}><button>{done&&<Check/>}</button><span className={`taskicon ${color}`}>{icon}</span><div><small>{top}</small><b>{title}</b></div><em><Clock3/> {meta}</em></article>}
function Summary({icon,cls,label,value,detail}:{icon:React.ReactNode,cls:string,label:string,value:string,detail:string}){return <article className="summary"><span className={cls}>{icon}</span><div><small>{label}</small><b>{value}</b><em><TrendingUp/> {detail}</em></div></article>}
function Counter({label,value,minus,plus}:{label:string,value:number,minus:()=>void,plus:()=>void}){return <label>{label}<div><button onClick={minus}>−</button><strong>{value}</strong><button onClick={plus}>+</button></div></label>}
