'use client';
import {useState} from 'react';
import {ArrowRight,BarChart3,BookOpen,Camera,Check,ChevronRight,Clock3,Flame,GraduationCap,House,ImagePlus,Lightbulb,Menu,MessageCircleMore,Play,Plus,Sparkles,Star,Target,TrendingUp,UsersRound,X} from 'lucide-react';

const subjects=[['Matematik','π','#7357c7','#eee9fb',68],['Türkçe','Aa','#ef725f','#ffebe6',84],['Fen','⚗','#238e89','#dff4ef',76],['İnkılap','✦','#d59a22','#fff2cf',73]] as const;
const coaches=[['MT','Matematik','Merve T.','Yeni değerlendirme','#7357c7'],['TÖ','Türkçe','Tolga Ö.','Rapor hazır','#ef725f'],['SA','Fen Bilimleri','Selin A.','İnceliyor','#238e89'],['EK','İnkılap Tarihi','Eren K.','Rapor hazır','#d59a22'],['DY','Din Kültürü','Derya Y.','Rapor hazır','#5377c6'],['CE','İngilizce','Cansu E.','Yeni değerlendirme','#a2589e']] as const;
function Ring({value}:{value:number}){return <div className="ring" style={{'--value':`${value*3.6}deg`} as React.CSSProperties}><div><strong>{value}</strong><span>%</span></div></div>}

export default function Home(){
 const [view,setView]=useState<'student'|'adult'>('student'); const [open,setOpen]=useState(false); const [saved,setSaved]=useState(false); const [count,setCount]=useState(20); const [wrong,setWrong]=useState(3);
 const save=()=>{setSaved(true);setTimeout(()=>{setSaved(false);setOpen(false)},900)};
 return <main className="shell">
  <aside className="side"><a className="brand" href="#"><span>R</span></a><nav><button className="active"><House/><i>Bugün</i></button><button><Target/><i>Konularım</i></button><button><BarChart3/><i>Gelişim</i></button><button><UsersRound/><i>Koçlarım</i></button></nav><button className="mini">D</button></aside>
  <section className="workspace"><header className="top"><button className="hamb"><Menu/></button><div className="switch"><button className={view==='student'?'on':''} onClick={()=>setView('student')}>Deniz</button><button className={view==='adult'?'on':''} onClick={()=>setView('adult')}>Yetişkin & Koç</button></div><div className="topright"><span><Flame/> 6 günlük seri</span><b>S</b></div></header>
  {view==='student'?<div className="page">
   <div className="welcome"><div><p className="eyebrow">2 EYLÜL · ÇARŞAMBA</p><h1>Selam Deniz! <span>Bugünkü rotan hazır.</span></h1></div><button className="primary" onClick={()=>setOpen(true)}><Plus/> Çalışma ekle</button></div>
   <section className="hero"><article className="daily"><div className="dailycopy"><span className="pill"><Sparkles/> BUGÜNÜN HEDEFİ</span><h2>Bir adım daha,<br/>hedefe biraz daha yakın.</h2><p>60 soruluk rotanın yarısından fazlası tamam. Harika gidiyorsun!</p><button onClick={()=>setOpen(true)}>Devam et <ArrowRight/></button></div><div className="dailyprogress"><Ring value={70}/><b>42 / 60 soru</b><small>18 soru kaldı</small></div></article>
   <article className="note"><div className="notehead"><span className="coachavatar">MT</span><div><small>Matematik koçun</small><b>Merve Öğretmen</b></div><MessageCircleMore/></div><blockquote>“Doğrusal denklemlerde adımların çok daha düzenli. Bugün kısa bir tekrar yeterli.”</blockquote><button>Haftalık değerlendirmeyi gör <ChevronRight/></button></article></section>
   <section className="route"><Heading kicker="BUGÜNKÜ ROTA" title="Üç küçük görev" color="coral" extra={<span className="done"><Check/> 1 / 3 tamam</span>}/><div className="tasks"><Task done icon="π" color="purple" top="MATEMATİK · 20 SORU" title="Doğrusal Denklemler" meta="18D · 2Y"/><Task icon="Aa" color="coral" top="TÜRKÇE · 15 SORU" title="Paragrafta Ana Düşünce" meta="20 dk"/><Task icon="⚗" color="teal" top="FEN · 10 SORU" title="DNA ve Genetik Kod" meta="15 dk"/></div></section>
   <section className="lower"><article className="weak"><Heading kicker="GÜÇLENDİRME ZAMANI" title="Birlikte toparlayalım" color="violet" extra={<Lightbulb/>}/><div className="weaktopic"><span>54<small>/100</small></span><div><small>MATEMATİK</small><b>Eşitsizlikler</b><p>Son 24 soruda en çok “işaret yönü” adımında zorlandın.</p></div></div><div className="video"><span><Play fill="currentColor"/></span><div><em><Star fill="currentColor"/> Koç seçimi</em><b>Eşitsizlikler · Hızlı konu anlatımı</b><small>18 dk · yüksek öğrenci etkileşimi</small></div><button><ChevronRight/></button></div></article>
   <article className="wrong"><span className="camera"><Camera/></span><div><p className="eyebrow tealtext">YANLIŞ DEFTERİM</p><h2>Takıldığın soruyu sakla</h2><p>Fotoğrafını çek, konusunu seç. Koçun görsün; zamanı gelince tekrar karşına çıksın.</p><button><ImagePlus/> Fotoğrafla soru ekle</button></div></article></section>
  </div>:<div className="page">
   <div className="welcome"><div><p className="eyebrow">HAFTALIK DEĞERLENDİRME · 26 AĞU–1 EYL</p><h1>Deniz’in haftası <span>bir bakışta.</span></h1></div><button className="outline">Raporu paylaş <ArrowRight/></button></div>
   <section className="summaries"><Summary icon={<BookOpen/>} cls="violetbg" label="ÇÖZÜLEN SORU" value="326" detail="%12 artış"/><Summary icon={<Target/>} cls="coralbg" label="HAFTALIK DOĞRULUK" value="%78" detail="4 puan artış"/><Summary icon={<GraduationCap/>} cls="tealbg" label="HAZIR KONULAR" value="18 / 42" detail="3 konu bu hafta"/></section>
   <section className="adultgrid"><article className="coachpanel"><Heading kicker="BRANŞ KOÇLARI" title="Uzman değerlendirmeleri" color="violet" extra={<span className="done">6 branş</span>}/><div className="coachtabs">{coaches.map((c,i)=><button key={c[1]} className={i===0?'selected':''} style={{'--coach':c[4]} as React.CSSProperties}><span>{c[0]}</span><div><b>{c[1]}</b><small>{c[3]}</small></div></button>)}</div><div className="evaluation"><div className="evalhead"><span className="coachavatar large">MT</span><div><small>LGS MATEMATİK KOÇU</small><h3>Merve Öğretmen’in değerlendirmesi</h3></div><span className="approved"><Check/> Onaylandı</span></div><p>Deniz bu hafta doğrusal denklemlerde belirgin ilerleme gösterdi. Eşitsizliklerde kuralı biliyor; negatif sayıyla işlem sırasında işaret yönünü kaçırıyor. Yeni konu eklemek yerine iki kısa pekiştirme oturumu daha verimli olacak.</p><div className="coachplan"><span><b>Gelecek hafta odağı</b><small>2 × 15 Eşitsizlikler + cuma kontrol testi</small></span><button>Planı görüntüle <ChevronRight/></button></div></div></article>
   <aside className="readiness"><Heading kicker="KONU HARİTASI" title="Hazır oluş" color="coral"/>{subjects.map(s=><div className="subject" key={s[0]}><span style={{background:s[3],color:s[2]}}>{s[1]}</span><div><b>{s[0]}</b><i><u style={{width:`${s[4]}%`,background:s[2]}}/></i></div><strong>{s[4]}</strong></div>)}<button className="link">Tüm konu haritası <ArrowRight/></button></aside></section>
  </div>}</section>
  {open&&<div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="modal" role="dialog" aria-modal="true"><button className="close" onClick={()=>setOpen(false)}><X/></button><span className="modalicon">π</span><p className="eyebrow">HIZLI KAYIT</p><h2>Ne çalıştın?</h2><label>Ders ve konu</label><button className="select"><span><b>Matematik</b><small>Doğrusal Denklemler</small></span><ChevronRight/></button><div className="numbers"><Counter label="Toplam soru" value={count} minus={()=>setCount(Math.max(0,count-5))} plus={()=>setCount(count+5)}/><Counter label="Yanlış" value={wrong} minus={()=>setWrong(Math.max(0,wrong-1))} plus={()=>setWrong(Math.min(count,wrong+1))}/></div><div className="result"><span><Check/> Doğru</span><b>{Math.max(0,count-wrong)}</b><span>Net</span><b>{(Math.max(0,count-wrong)-wrong/3).toFixed(2)}</b></div><button className={`save ${saved?'saved':''}`} onClick={save}>{saved?<><Check/> Kaydedildi!</>:<>Çalışmayı kaydet <ArrowRight/></>}</button></section></div>}
 </main>
}
function Heading({kicker,title,color,extra}:{kicker:string,title:string,color:string,extra?:React.ReactNode}){return <div className="heading"><div><p className={`eyebrow ${color}`}>{kicker}</p><h2>{title}</h2></div>{extra}</div>}
function Task({done,icon,color,top,title,meta}:{done?:boolean,icon:string,color:string,top:string,title:string,meta:string}){return <article className={`task ${done?'complete':''}`}><button>{done&&<Check/>}</button><span className={`taskicon ${color}`}>{icon}</span><div><small>{top}</small><b>{title}</b></div><em><Clock3/> {meta}</em></article>}
function Summary({icon,cls,label,value,detail}:{icon:React.ReactNode,cls:string,label:string,value:string,detail:string}){return <article className="summary"><span className={cls}>{icon}</span><div><small>{label}</small><b>{value}</b><em><TrendingUp/> {detail}</em></div></article>}
function Counter({label,value,minus,plus}:{label:string,value:number,minus:()=>void,plus:()=>void}){return <label>{label}<div><button onClick={minus}>−</button><strong>{value}</strong><button onClick={plus}>+</button></div></label>}
