'use client';
import {useEffect,useMemo,useState} from 'react';
import {BookCheck,CheckCircle2,ExternalLink,RefreshCw,Sparkles} from 'lucide-react';
import {lgsCurriculum} from '@/lib/lgs-curriculum';
import {lgsExamSubjects} from '@/lib/lgs-question-catalog';

type Question={id:number;year:number;subjectId:string;questionNumber:number;unit:string|null;topic:string|null;tagStatus:string;officialUrl:string};
type MiniQuestion={id:number;year:number;subjectId:string;questionNumber:number;unit:string;topic:string;officialUrl:string};

export function QuestionCatalog(){
 const [year,setYear]=useState(2026),[subjectId,setSubjectId]=useState('matematik'),[questions,setQuestions]=useState<Question[]>([]),[total,setTotal]=useState(0),[approved,setApproved]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[mini,setMini]=useState<MiniQuestion[]>([]);
 const curriculum=useMemo(()=>lgsCurriculum.find(x=>x.id===subjectId)!,[subjectId]);
 const load=async()=>{setBusy(true);setMessage('');try{const response=await fetch(`/api/question-catalog?year=${year}&subject=${subjectId}`);const data=await response.json() as {error?:string;questions:Question[];totals:{total:number;approved:number}};if(!response.ok)throw new Error(data.error);setQuestions(data.questions);setTotal(data.totals.total);setApproved(data.totals.approved)}catch(error){setMessage(error instanceof Error?error.message:'Katalog yüklenemedi.')}finally{setBusy(false)}};
 // Filtre değiştiğinde sunucudaki katalog görünümünü yeniler.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[year,subjectId]);
 const initialize=async()=>{setBusy(true);const response=await fetch('/api/question-catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'initialize'})});const data=await response.json() as {error?:string};setMessage(response.ok?'2018–2026 kataloğu hazırlandı.':data.error??'Katalog kurulamadı.');setBusy(false);if(response.ok)await load()};
 const approveQuestion=async(question:Question,unit:string,topic:string)=>{const response=await fetch('/api/question-catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'approve',id:question.id,unit,topic})});if(response.ok)await load();else{const data=await response.json() as {error?:string};setMessage(data.error??'Soru onaylanamadı.')}};
 const makeMini=async()=>{setBusy(true);const response=await fetch('/api/mini-test');const data=await response.json() as {questions?:MiniQuestion[];message?:string};setMini(data.questions??[]);setMessage(data.message??'');setBusy(false)};
 return <div className="page catalog-page"><div className="welcome"><div><p className="eyebrow">RESMÎ LGS SORU KATALOĞU</p><h1>Yanlışlardan <span>hedefli mini denemeye.</span></h1></div><span className="role-badge">Yetişkin & koç onaylı</span></div>
 <section className="catalog-summary"><article><BookCheck/><div><small>KATALOG</small><b>{total||810} soru</b><span>2018–2026 · MEB kaynakları</span></div></article><article><CheckCircle2/><div><small>ONAYLANAN</small><b>{approved} soru</b><span>Ünite ve konu eşleştirmesi</span></div></article><button onClick={makeMini} disabled={busy}><Sparkles/> Yanlışlarımdan mini deneme hazırla</button></section>
 {message&&<p className="catalog-message">{message}</p>}
 {total===0?<section className="catalog-empty"><BookCheck/><h2>Katalog kurulmaya hazır</h2><p>Dokuz sınav yılındaki 810 sorunun kimlik kartlarını oluşturur. Soru metni ve görseli kopyalanmaz; resmî MEB bağlantısı saklanır.</p><button onClick={initialize} disabled={busy}>{busy?<RefreshCw className="spin"/>:<Sparkles/>} Kataloğu şimdi kur</button></section>:<><section className="catalog-filters"><label>Yıl<select value={year} onChange={e=>setYear(Number(e.target.value))}>{Array.from({length:9},(_,i)=>2018+i).reverse().map(x=><option key={x}>{x}</option>)}</select></label><label>Ders<select value={subjectId} onChange={e=>setSubjectId(e.target.value)}>{lgsExamSubjects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><span>{busy?'Yükleniyor…':`${questions.length} soru`}</span></section><div className="catalog-list">{questions.map(question=><QuestionRow key={question.id} question={question} curriculum={curriculum} onApprove={approveQuestion}/>)}</div></>}
 {mini.length>0&&<section className="mini-test"><h2>Mini deneme seçkisi</h2><p>Yanlış Defteri’ndeki en sık konulara göre öğretmen onaylı resmî sorular.</p>{mini.map((q,i)=><a key={q.id} href={q.officialUrl} target="_blank" rel="noreferrer"><b>{i+1}. {q.year} {lgsExamSubjects.find(x=>x.id===q.subjectId)?.name} · {q.questionNumber}. soru</b><span>{q.unit} · {q.topic}</span><ExternalLink/></a>)}</section>}
 </div>
}

function QuestionRow({question,curriculum,onApprove}:{question:Question;curriculum:(typeof lgsCurriculum)[number];onApprove:(question:Question,unit:string,topic:string)=>Promise<void>}){const [unit,setUnit]=useState(question.unit??curriculum.units[0].name);const current=curriculum.units.find(x=>x.name===unit)??curriculum.units[0];const [topic,setTopic]=useState(question.topic??current.topics[0]);const chooseUnit=(name:string)=>{setUnit(name);setTopic(curriculum.units.find(x=>x.name===name)!.topics[0])};return <article className={`catalog-row ${question.tagStatus==='approved'?'approved':''}`}><div className="question-id"><span>{question.year}</span><b>{question.questionNumber}. soru</b><a href={question.officialUrl} target="_blank" rel="noreferrer">MEB’de aç <ExternalLink/></a></div><label>Ünite<select value={unit} onChange={e=>chooseUnit(e.target.value)}>{curriculum.units.map(x=><option key={x.name}>{x.name}</option>)}</select></label><label>Konu<select value={topic} onChange={e=>setTopic(e.target.value)}>{current.topics.map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>onApprove(question,unit,topic)}>{question.tagStatus==='approved'?<><CheckCircle2/> Onaylandı</>:<><CheckCircle2/> Onayla</>}</button></article>}
