export type CurriculumUnit = { name: string; topics: string[] };
export type CurriculumSubject = { id: string; name: string; shortName: string; icon: string; color: string; units: CurriculumUnit[] };

export const lgsCurriculum: CurriculumSubject[] = [
  { id: 'paragraf', name: 'Paragraf', shortName: 'Paragraf', icon: '¶', color: '#ef725f', units: [] },
  { id: 'turkce', name: 'Türkçe', shortName: 'Türkçe', icon: 'Aa', color: '#ef725f', units: [
    { name: 'Sözcükte Anlam', topics: ['Çok Anlamlılık ve Sözcükte Anlam İlişkileri', 'Sözcük Gruplarında Anlam', 'Söz Sanatları', 'Deyimler ve Atasözleri'] },
    { name: 'Cümlede Anlam', topics: ['Cümlede Anlam Özellikleri', 'Cümle Yorumu', 'Anlatımına Göre Cümleler', 'Cümle Birleştirme, Tamamlama ve Oluşturma'] },
    { name: 'Paragrafta Anlam', topics: ['Paragrafın Anlam Yönü', 'Paragrafın Yapı Yönü', 'Paragrafın Anlatım Biçimi ve Düşünceyi Geliştirme Yolları', 'Paragrafta Dil ve Anlatım – Hikâye Unsurları'] },
    { name: 'Görsel Okuma / Sözel Mantık', topics: ['Görsel Okuma', 'Tablo ve Grafik Yorumlama', 'Sözel Mantık – Muhakeme'] },
    { name: 'Fiilimsiler (Eylemsiler)', topics: ['İsim-Fiiller', 'Sıfat-Fiiller', 'Zarf-Fiiller'] },
    { name: 'Cümlenin Öğeleri', topics: ['Temel Öğeler', 'Yardımcı Öğeler – Ara Söz – Vurgu'] },
    { name: 'Fiilde (Eylemde) Çatı', topics: ['Öznelerine Göre Fiiller', 'Nesnelerine Göre Fiiller'] },
    { name: 'Cümle Türleri', topics: ['Yüklemin Yerine, Türüne ve Anlamına Göre Cümleler', 'Yapısına Göre Cümleler'] },
    { name: 'Anlatım Bozuklukları', topics: ['Yapıya Dayalı Anlatım Bozuklukları'] },
    { name: 'Yazım Kuralları', topics: ['“De” ve “Ki” Bağlaçlarının Yazımı', '“Mi” Soru Ekinin Yazımı', 'Büyük Harflerin Kullanıldığı Yerler', 'Birleşik Sözcüklerin Yazımı', 'Birleşik Fiillerin Yazımı', 'Pekiştirmeli Sözcüklerin Yazımı', 'Kısaltmaların Yazımı', 'Sayıların Yazımı'] },
    { name: 'Noktalama İşaretleri', topics: ['Noktalama İşaretleri'] },
    { name: 'Metin Türleri', topics: ['Metin Türleri'] },
  ]},
  { id: 'matematik', name: 'Matematik', shortName: 'Matematik', icon: 'π', color: '#7357c7', units: [
    { name: 'Çarpanlar ve Katlar & Üslü İfadeler', topics: ['Pozitif Tam Sayıların Çarpanları', 'EBOB ve EKOK', 'Aralarında Asal Sayılar', 'Tam Sayıların Tam Sayı Kuvvetleri', 'Üslü İfadeler ile İlgili Temel Kurallar', 'Ondalık Gösterimleri Çözümleme', 'Bilimsel Gösterim'] },
    { name: 'Kareköklü İfadeler & Veri Analizi', topics: ['Tam Kare Sayılar ve Karekökleri', 'Tam Kare Olmayan Kareköklerin Bulunduğu Aralıklar', 'Kareköklü İfadeyi a√b Şeklinde Yazma', 'Kareköklü İfadelerde Çarpma ve Bölme', 'Kareköklü İfadelerde Toplama ve Çıkarma', 'Sonucu Doğal Sayı Yapan Çarpanlar', 'Ondalık İfadelerin Karekökleri', 'Gerçek Sayılar', 'Çizgi ve Sütun Grafikleri', 'Verilerin Farklı Gösterimleri'] },
    { name: 'Basit Olayların Olma Olasılığı & Cebirsel İfadeler', topics: ['Basit Olayların Olma Olasılığı', 'Basit Cebirsel İfadeler ve Çarpma İşlemi', 'Özdeşlikler', 'Cebirsel İfadeleri Çarpanlara Ayırma'] },
    { name: 'Doğrusal Denklemler & Eşitsizlikler', topics: ['Birinci Dereceden Bir Bilinmeyenli Denklemler', 'Koordinat Sistemi', 'Doğrusal İlişki Bulunan Değişkenler', 'Doğrusal Denklemlerin Grafiği', 'Doğrusal İlişki İçeren Gerçek Hayat Durumları', 'Eğim', 'Birinci Dereceden Bir Bilinmeyenli Eşitsizlikler'] },
    { name: 'Üçgenler & Eşlik ve Benzerlik', topics: ['Üçgende Açıortay, Kenarortay ve Yükseklik', 'Üçgenlerin Kenarları Arasındaki İlişkiler', 'Kenar Uzunlukları ile Açı Ölçüleri Arasındaki İlişkiler', 'Üçgen Çizimi', 'Pisagor Bağıntısı', 'Eşlik ve Benzerlik'] },
    { name: 'Dönüşüm Geometrisi & Geometrik Cisimler', topics: ['Öteleme', 'Yansıma', 'Çokgenlerin Öteleme ve Yansıma Görüntüleri', 'Dik Prizma', 'Dik Dairesel Silindirin Temel Elemanları ve Açınımı', 'Dik Dairesel Silindirin Yüzey Alanı', 'Dik Dairesel Silindirin Hacmi', 'Dik Piramit', 'Dik Koni'] },
  ]},
  { id: 'fen', name: 'Fen Bilimleri', shortName: 'Fen', icon: '⚗', color: '#238e89', units: [
    { name: 'Mevsimler ve İklim', topics: ['Mevsimlerin Oluşumu', 'İklim ve Hava Olayları Arasındaki Fark', 'Hava Olayları', 'İklim', 'İklim Değişikliği'] },
    { name: 'DNA ve Genetik Kod', topics: ['Nükleotid, Gen, DNA ve Kromozom İlişkisi', 'DNA’nın Yapısı', 'DNA’nın Kendini Eşlemesi', 'Kalıtım ve Kalıtımla İlgili Kavramlar', 'Tek Karakter Çaprazlamaları', 'Akraba Evliliklerinin Genetik Sonuçları', 'Mutasyon', 'Modifikasyon', 'Mutasyon ve Modifikasyon Arasındaki Fark', 'Adaptasyon', 'Genetik Mühendisliği ve Biyoteknoloji'] },
    { name: 'Basınç', topics: ['Katı Basıncı', 'Sıvı Basıncı', 'Sıvı Basıncına Etki Eden Etmenler', 'Gazların Basıncı', 'Basınç Özelliklerinden Yararlanan Teknolojiler'] },
    { name: 'Madde ve Endüstri', topics: ['Periyodik Sistem', 'Periyotlar ve Gruplar', 'Metaller, Ametaller ve Yarı Metaller', 'Fiziksel ve Kimyasal Değişimler', 'Kimyasal Tepkimeler', 'Asit ve Bazların Genel Özellikleri', 'pH Değerleri', 'Asit Yağmurları', 'Isı ve Sıcaklık', 'Öz Isı', 'Hâl Değişimleri', 'Türkiye’de Kimya Endüstrisi'] },
    { name: 'Basit Makineler', topics: ['Basit Makinelerin Sağladığı Avantajlar', 'Makaralar ve Palangalar', 'Kaldıraçlar', 'Eğik Düzlem', 'Çıkrık', 'Bileşik Makine Tasarlama'] },
    { name: 'Enerji Dönüşümleri ve Çevre Bilimi', topics: ['Besin Zinciri ve Enerji Akışı', 'Ekoloji Piramitleri ve Biyolojik Birikim', 'Fotosentez', 'Fotosentez Hızını Etkileyen Faktörler', 'Canlılarda Solunum', 'Madde Döngüleri', 'Küresel İklim Değişikliği', 'Ekolojik Ayak İzi', 'Kaynakların Tasarruflu Kullanımı', 'Geri Dönüşüm'] },
    { name: 'Elektrik Yükleri ve Elektrik Enerjisi', topics: ['Elektriklenmenin Uygulama Alanları', 'Elektrik Yükleri ve Etkileşimleri', 'Elektriklenme Çeşitleri', 'Cisimlerin Elektrik Yükleri', 'Topraklama', 'Elektrik Enerjisinin Isı, Işık ve Harekete Dönüşümü', 'Güç Santrallerinde Elektrik Üretimi', 'Elektrik Enerjisinin Bilinçli Kullanımı'] },
  ]},
  { id: 'inkilap', name: 'T.C. İnkılap Tarihi ve Atatürkçülük', shortName: 'İnkılap', icon: '✦', color: '#d59a22', units: [
    { name: 'Bir Kahraman Doğuyor', topics: ['Avrupa’daki Gelişmeler ve Osmanlı Devleti', 'Mustafa Kemal’in Çocukluk ve Öğrenim Hayatı', 'Mustafa Kemal’in Askerlik Hayatı'] },
    { name: 'Millî Uyanış: Bağımsızlık Yolunda Atılan Adımlar', topics: ['I. Dünya Savaşı ve Osmanlı Devleti', 'Mondros Ateşkes Antlaşması ve İşgaller', 'Kuvâ-yı Millîye ve Cemiyetler', 'Millî Mücadele’nin Hazırlık Dönemi', 'Misakımillî ve TBMM'] },
    { name: 'Millî Bir Destan: Ya İstiklal Ya Ölüm!', topics: ['Doğu ve Güney Cepheleri', 'Batı Cephesi', 'Maarif Kongresi ve Tekâlif-i Millîye', 'Mudanya Ateşkes Antlaşması ve Lozan Barış Antlaşması'] },
    { name: 'Atatürkçülük ve Çağdaşlaşan Türkiye', topics: ['Atatürk İlkeleri', 'Siyasi ve Hukuki İnkılaplar', 'Eğitim, Kültür ve Toplumsal İnkılaplar', 'Ekonomi Alanındaki Gelişmeler'] },
    { name: 'Demokratikleşme Çabaları', topics: ['Çok Partili Hayata Geçiş Denemeleri', 'Cumhuriyet’e Yönelik Tehditler'] },
    { name: 'Atatürk Dönemi Türk Dış Politikası', topics: ['Türk Dış Politikasının Temel İlkeleri', 'Dış Politikadaki Gelişmeler', 'Hatay’ın Ana Vatana Katılması'] },
    { name: 'Atatürk’ün Ölümü ve Sonrası', topics: ['Atatürk’ün Ölümü ve Ölümünün Yankıları', 'Atatürk’ün Eserleri', 'İkinci Dünya Savaşı ve Türkiye’nin Denge Siyaseti', 'İkinci Dünya Savaşı’nın Türkiye’ye Etkileri', 'Türkiye’de Çok Partili Siyasi Hayata Geçiş'] },
  ]},
  { id: 'din', name: 'Din Kültürü ve Ahlak Bilgisi', shortName: 'Din', icon: '☾', color: '#5377c6', units: [
    { name: 'Kader İnancı', topics: ['Kader ve Kaza İnancı', 'İnsanın İradesi ve Kader', 'Kaderle İlgili Kavramlar', 'Bir Peygamber Tanıyorum: Hz. Musa', 'Bir Ayet Tanıyorum: Ayetelkürsi ve Anlamı'] },
    { name: 'Zekât ve Sadaka', topics: ['İslam’ın Paylaşmaya ve Yardımlaşmaya Verdiği Önem', 'Zekât ve Sadaka İbadeti', 'Zekât ve Sadakanın Bireysel ve Toplumsal Faydaları', 'Bir Peygamber Tanıyorum: Hz. Şuayb', 'Bir Sure Tanıyorum: Maun Suresi ve Anlamı'] },
    { name: 'Din ve Hayat', topics: ['Din, Birey ve Toplum', 'Dinin Temel Gayesi', 'Bir Peygamber Tanıyorum: Hz. Yusuf', 'Bir Sure Tanıyorum: Asr Suresi ve Anlamı'] },
    { name: 'Hz. Muhammed’in Örnekliği', topics: ['Doğruluğu ve Güvenilir Kişiliği', 'Merhametli ve Affedici Oluşu', 'İstişareye Önem Vermesi', 'Davasındaki Cesaret ve Kararlılığı', 'Hakkı Gözetmedeki Hassasiyeti', 'İnsanlara Değer Vermesi', 'Bir Sure Tanıyorum: Kureyş Suresi ve Anlamı'] },
    { name: 'Kur’an-ı Kerim ve Özellikleri', topics: ['İslam Dininin Temel Kaynakları', 'Kur’an-ı Kerim’in Ana Konuları', 'Kur’an-ı Kerim’in Temel Özellikleri', 'Bir Peygamber Tanıyorum: Hz. Nuh'] },
  ]},
  { id: 'ingilizce', name: 'İngilizce', shortName: 'İngilizce', icon: 'EN', color: '#a2589e', units: [
    { name: 'Unit 1: Friendship', topics: ['Accepting and Refusing', 'Apologizing and Giving Explanations'] },
    { name: 'Unit 2: Teen Life', topics: ['Daily Routines', 'Likes and Dislikes'] },
    { name: 'Unit 3: In the Kitchen', topics: ['Describing Processes', 'Making Simple Inquiries'] },
    { name: 'Unit 4: On the Phone', topics: ['Telephone Conversations', 'Leaving a Message'] },
    { name: 'Unit 5: The Internet', topics: ['Internet Habits', 'Online Safety'] },
    { name: 'Unit 6: Adventures', topics: ['Preferences', 'Comparisons'] },
    { name: 'Unit 7: Tourism', topics: ['Describing Places', 'Experiences'] },
    { name: 'Unit 8: Chores', topics: ['Responsibilities', 'Obligations'] },
    { name: 'Unit 9: Science', topics: ['Scientific Achievements', 'Past Events'] },
    { name: 'Unit 10: Natural Forces', topics: ['Natural Disasters', 'Predictions'] },
  ]},
];
